#!/usr/bin/python

import os
import sys

if len(sys.argv) != 3:
    print("Usage: " + sys.argv[0] + "df_path" + " service")
    sys.exit(1)

df_path = sys.argv[1]
service = sys.argv[2]

install_path = df_path + "/usr/local/" + service

if __name__ == '__main__':

    print("./service " + df_path +" "+ service)
    os.system("./service " + df_path +" "+ service)
